name: Build

on:
  push:
    branches:
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
      - ci/*
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Run lint checks
        run: ./gradlew lint --no-daemon --stacktrace

      - name: Run local unit tests
        run: ./gradlew test testDebugUnitTest --no-daemon --stacktrace

      # Upload lint report if lint fails
      - name: Upload Lint Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: '**/build/reports/lint-results-*.html'

      # Upload test results if tests fail
      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/test-results/testDebugUnitTest'
